{{- if .Values.pushgateway.podDisruptionBudget.enabled }}
apiVersion: extensions/v1beta1
kind: PodDisruptionBudget
metadata:
  name: {{ template "prometheus.pushgateway.fullname" . }}
  labels:
    {{- include "prometheus.pushgateway.labels" . | nindent 4 }}
spec:
  maxUnavailable: {{ .Values.pushgateway.podDisruptionBudget.maxUnavailable }}
  selector:
    matchLabels:
      {{- include "prometheus.pushgateway.labels" . | nindent 6 }}
{{- end }}
